import Image from "next/image";
import BoxContainer from "./../BoxContainer";

function ShowCard({ title, imgSrc, imgAlt, children }) {
  return (
    <div className="max-w-[280px] flex flex-col items-center justify-start gap-2">
      <Image src={imgSrc} alt={imgAlt} width={72} height={72} />
      <p className="font-medium text-lg">{title}</p>
      <p className="text-[hsl(0,_0%,_30%)] text-center">{children}</p>
    </div>
  );
}
export default function HelpBar() {
  return (
    <div className="p-4 bg-[#146EB4]/10">
      <BoxContainer className="flex flex-row items-start justify-center gap-8 flex-wrap">
        <ShowCard title="Search" imgSrc="/public/icons/layout.svg" imgAlt="icon layout">
          Simply add a keyword or a term related to your business in the slogan
          maker search box. Wait for the magic to happen.
        </ShowCard>
        <ShowCard
          title="Select"
          imgSrc="/public/icons/cursor.svg"
          imgAlt="icon cursor"
        >
          Choose from thousands of options generated by the slogan maker that
          fit your needs.
        </ShowCard>
        <ShowCard title="Stand out" imgSrc="/public/icons/ups.svg" imgAlt="icons ups">
          Congrats on your new slogan. {"It's "}time to win the world!
        </ShowCard>
      </BoxContainer>
    </div>
  );
}
